baseURL = "https://youthful-albattani-26ca31.netlify.app/"
languageCode = "en-us"
title = "Carrie Rennolds"

[params]
  # images
  header = "/images/header/header.png"
  icon = "/images/header/icon.png"
  # colors
  background = "pink"
  border = "black"
  # css
  custom_css = ["css/artist-baltimore-main.css", 
                "css/fake-new-yorker-header.css",
                "css/necroprancer-borders.css",
                "css/illustration-pedagogy-flex.css"]

[menu]
  [[menu.main]]
    parent="fantasy"
    name = "Sybil Press"
    pre = "<img class=tiny-icon src=/images/sybil-press-logo.jpg></img>"
    url = "http://www.sybilpress.org/"
    weight = 1
  [[menu.main]]
    name = "Fake New Yorker Volume 1"
    parent="fantasy"
    url = "http://www.sybilpress.org/bookstore/fake-new-yorker-vol-2-2018-2nd-printing"
    weight = 2
  [[menu.main]]
    name = "Fake New Yorker Volume 2"
    parent="fantasy"
    url = "http://www.sybilpress.org/bookstore/fake-new-yorker-vol-2-1st-edition"
    weight = 3